import os

from dotenv import load_dotenv


load_dotenv()


# =========================
# TRADING MODE / GLOBAL GATES
# =========================
_raw_trading_mode = os.getenv("TRADING_MODE", "PAPER")
# Backward compatibility with older env values.
if _raw_trading_mode == "PAPER_TRADING":
    _raw_trading_mode = "PAPER"
TRADING_MODE = _raw_trading_mode  # SIGNAL_ONLY | PAPER | LIVE
ENABLE_LIVE_TRADING = os.getenv("ENABLE_LIVE_TRADING", "false").lower() == "true"
LIVE_ENABLED = os.getenv("LIVE_ENABLED", "false").lower() == "true"
GLOBAL_KILL_SWITCH = os.getenv("GLOBAL_KILL_SWITCH", "false").lower() == "true"
ALLOW_UNVALIDATED_STRATEGY = False


ETRADE_CONSUMER_KEY = os.getenv("ETRADE_CONSUMER_KEY")
ETRADE_CONSUMER_SECRET = os.getenv("ETRADE_CONSUMER_SECRET")
ETRADE_ENV = os.getenv("ETRADE_ENV", "sandbox")

# ALPACA MARKET DATA
ALPACA_API_KEY = os.getenv("ALPACA_API_KEY")
ALPACA_SECRET_KEY = os.getenv("ALPACA_SECRET_KEY")

ALPACA_BASE_URL = "https://paper-api.alpaca.markets"
ALPACA_DATA_URL = "https://data.alpaca.markets"
ALPACA_DATA_FEED = os.getenv("ALPACA_DATA_FEED", "iex")

# PLATFORM INTEGRATIONS
BROKER_PROVIDER = os.getenv("BROKER_PROVIDER", "csv")  # csv | alpaca_paper
SUPABASE_ENABLED = os.getenv("SUPABASE_ENABLED", "false").lower() == "true"
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
# =========================
# ACCOUNT SETTINGS
# =========================
INITIAL_CAPITAL = float(os.getenv("INITIAL_CAPITAL", "10000"))
# Legacy names kept for compatibility; PDT $25k floor no longer enforced.
PDT_MIN_EQUITY = 0
MIN_EQUITY_BUFFER = 0
DO_NOT_TRADE_BELOW_EQUITY = 0


# =========================
# RISK SETTINGS
# =========================
MAX_POSITIONS = 2
MAX_CAPITAL_PER_TRADE = 0.10
MAX_PORTFOLIO_EXPOSURE = 0.40
MAX_DAILY_LOSS_PERCENT = 0.01
MAX_DAILY_LOSS_DOLLARS = 150
MAX_DRAWDOWN_PERCENT = 0.05
MAX_TRADES_PER_DAY = 5
LOSING_STREAK_COOLDOWN = 2
LOSING_STREAK_COOLDOWN_MINUTES = 120
MIN_TRADE_DOLLARS = 250
MAX_SECTOR_EXPOSURE = 0.25


# =========================
# MARKET SCANNER SETTINGS
# =========================
MIN_PRICE = 10.00
MAX_PRICE = 200.00
MIN_DAILY_VOLUME = 1000000
MIN_ABS_PERCENT_CHANGE = 0.10
MAX_SPREAD_PERCENT = 0.60
MIN_AVERAGE_VOLUME = 5000

MAX_SYMBOLS_TO_SCAN = 0
SNAPSHOT_POOL_SIZE = 120
MAX_DEEP_SCORE_CANDIDATES = 50
TOP_CANDIDATES_TO_TRADE = 20

INTRADAY_MINUTES_BACK = 180
MODEL_MINUTES_BACK = 180
BUY_START_TIME = "10:00"
BUY_END_TIME = "14:45"
FORCE_CLOSE_TIME = "15:55"


# =========================
# SNAPSHOT SCORING WEIGHTS
# =========================
WEIGHT_MOMENTUM = 0.6
WEIGHT_LIQUIDITY = 1.0
WEIGHT_SPREAD = 1.2

WEIGHT_SNAPSHOT_SCORE = 0.20
WEIGHT_INTRADAY_SCORE = 0.80


# =========================
# BUY / SELL THRESHOLDS
# =========================
BUY_SCORE_THRESHOLD = 7.0
RELAXED_BUY_SCORE_THRESHOLD = 5.5
RELAXED_BUY_AFTER_TIME = "13:30"
SELL_SCORE_THRESHOLD = -1.0
MIN_INTRADAY_SCORE = 1.5


# =========================
# PULLBACK STRATEGY FILTERS
# =========================
MIN_RETURN_3M = 0.0005
MIN_RETURN_5M = -0.0025
MIN_RETURN_15M = -0.015
MIN_RELATIVE_VOLUME = 0.80
MAX_RELATIVE_VOLUME = 2.10
REQUIRE_ABOVE_VWAP = True
MIN_BREAKOUT_POSITION = 0.15
MAX_BREAKOUT_POSITION = 0.38

MIN_DISTANCE_TO_MA50 = -0.03
MAX_DISTANCE_TO_MA50 = 0.06
MAX_BAR_RANGE_PERCENT = 0.035
MIN_EMA_RATIO = 0.9985


# =========================
# POSITION MANAGEMENT
# =========================
STOP_LOSS_PERCENT = 0.006
PROFIT_TARGET_PERCENT = 0.008

MIN_HOLD_MINUTES = 8
MAX_HOLD_MINUTES = 120
MAX_HOLD_DAYS = 3

MIN_SCORE_DROP_TO_SELL = 6.0
PROFIT_PROTECTION_SCORE_DROP = 4.5
PROFIT_PROTECTION_TRIGGER = 0.006
WEAKNESS_EXIT_HOLD_MINUTES = 12

REPLACEMENT_SCORE_BUFFER = 2.0
COOLDOWN_MINUTES = 90
MAX_BUYS_PER_SYMBOL_PER_DAY = 1


# =========================
# BACKTEST SETTINGS
# =========================
BACKTEST_SLIPPAGE_PERCENT = 0.0005
BACKTEST_COMMISSION_PER_SHARE = 0.0


# =========================
# VALIDATION GATES
# =========================
MIN_PAPER_TRADES_BEFORE_LIVE = 100
MIN_PROFIT_FACTOR_BEFORE_LIVE = 1.25
MIN_EXPECTANCY_BEFORE_LIVE = 0.0
MAX_VALIDATED_DRAWDOWN = 0.08


# =========================
# ACTIVE STRATEGY
# =========================
ACTIVE_STRATEGY = os.getenv("ACTIVE_STRATEGY", "momentum_scan_v1")
SCAN_MODE = os.getenv("SCAN_MODE", "market")
TRADE_SYMBOLS = []
MARKET_REGIME_SYMBOL = "QQQ"
USE_DAILY_REGIME = False
DAILY_REGIME_LAG_DAYS = 1

# Swing (daily trend) settings
SWING_ENTRY_START = "09:35"
SWING_ENTRY_END = "10:15"
SWING_STOP_LOSS_PERCENT = 0.08
SWING_PROFIT_TARGET_PERCENT = 0.50
SWING_MAX_HOLD_MINUTES = 60 * 24 * 30


# =========================
# MOMENTUM BREAKOUT STRATEGY
# =========================
STRATEGY_NAME = "momentum_breakout_v1"
RISK_REWARD_MINIMUM = 2.0
RSI_MIN = 50.0
RSI_MAX = 70.0
MOMENTUM_RVOL_MIN = 1.0
BREAKOUT_LOOKBACK = 20
REQUIRE_BREAKOUT = True
ATR_PERIOD = 14
ATR_STOP_MULTIPLE = 1.2
ATR_EXTREME_PERCENT = 0.025
TRAILING_STOP_R_MULTIPLE = 1.0


# =========================
# OPENING RANGE VWAP MOMENTUM v1
# =========================
ORVWAP_STRATEGY_NAME = "opening_range_vwap_momentum_v1"
ORVWAP_UNIVERSE = [
    "SPY",
    "QQQ",
    "NVDA",
    "TSLA",
    "AMD",
    "AAPL",
    "META",
    "MSFT",
    "AMZN",
]
# Trade these; SPY/QQQ are market-filter symbols only.
ORVWAP_TRADE_SYMBOLS = [
    "NVDA",
    "TSLA",
    "AMD",
    "AAPL",
    "META",
    "MSFT",
    "AMZN",
]
ORVWAP_EXCLUDED_SYMBOLS = {
    symbol.strip().upper()
    for symbol in os.getenv("ORVWAP_EXCLUDED_SYMBOLS", "").split(",")
    if symbol.strip()
}
ORVWAP_BLOCKED_ENTRY_HOURS_ET = {
    int(value.strip())
    for value in os.getenv("ORVWAP_BLOCKED_ENTRY_HOURS_ET", "").split(",")
    if value.strip()
}
ORVWAP_TECH_SYMBOLS = {
    "NVDA",
    "TSLA",
    "AMD",
    "AAPL",
    "META",
    "MSFT",
    "AMZN",
}
ORVWAP_OPENING_RANGE_START = "09:30"
ORVWAP_OPENING_RANGE_END = "09:35"
ORVWAP_ENTRY_START = "09:35"
ORVWAP_ENTRY_END = "10:30"
ORVWAP_FORCE_CLOSE_TIME = "15:55"
ORVWAP_VOLUME_LOOKBACK = 20
ORVWAP_MIN_VOLUME_RATIO = float(os.getenv("ORVWAP_MIN_VOLUME_RATIO", "1.8"))
ORVWAP_OR_BREAKOUT_BUFFER_PCT = float(os.getenv("ORVWAP_OR_BREAKOUT_BUFFER_PCT", "0.0"))
ORVWAP_MAX_SPREAD_PCT = float(os.getenv("ORVWAP_MAX_SPREAD_PCT", "0.15"))
ORVWAP_MAX_VWAP_EXTENSION_ATR = float(os.getenv("ORVWAP_MAX_VWAP_EXTENSION_ATR", "1.5"))
ORVWAP_STOP_PCT = 0.004
ORVWAP_ATR_STOP_MULTIPLE = 0.5
ORVWAP_STOP_SELECTION = os.getenv("ORVWAP_STOP_SELECTION", "widest")
ORVWAP_EXIT_ON_VWAP_LOSS = os.getenv("ORVWAP_EXIT_ON_VWAP_LOSS", "false").lower() == "true"
ORVWAP_TARGET_R = float(os.getenv("ORVWAP_TARGET_R", "2.0"))
ORVWAP_USE_TRAILING_AFTER_1R = os.getenv("ORVWAP_USE_TRAILING_AFTER_1R", "false").lower() == "true"
ORVWAP_RISK_PER_TRADE_PCT = float(os.getenv("ORVWAP_RISK_PER_TRADE_PCT", "0.00375"))
ORVWAP_MAX_POSITIONS = 1
ORVWAP_MAX_TRADES_PER_DAY = 3
ORVWAP_MAX_LOSING_TRADES_PER_DAY = 2
ORVWAP_MARKET_FILTER_SYMBOL = "SPY"
ORVWAP_TECH_FILTER_SYMBOL = "QQQ"
ORVWAP_SIGNAL_LOG_FILE = os.getenv("ORVWAP_SIGNAL_LOG_FILE", "logs/orvwap_signals.csv")
ORVWAP_REPORT_DIR = os.getenv("ORVWAP_REPORT_DIR", "research_results_orvwap")


# =========================
# ORB PULLBACK CONTINUATION v1 (RESEARCH ONLY)
# =========================
# This strategy is research-only by construction. It is never assigned to
# ACTIVE_STRATEGY for paper/live execution and it does not add any path to
# LIVE trading. It must clear validation/performance_gate.py (and the
# ORB-PBC specific gates in validation/orb_pbc_gate.py) before it can even be
# considered a PAPER_CANDIDATE. See ORB_PBC_RESEARCH_ONLY below.
ORB_PBC_STRATEGY_NAME = "orb_pullback_continuation_v1"
ORB_PBC_RESEARCH_ONLY = True
ORB_PBC_SIDE = "long_only"
ORB_PBC_SYMBOLS = ["NVDA", "META", "AMD", "TSLA"]
ORB_PBC_OPTIONAL_SYMBOLS = ["AAPL", "MSFT", "AMZN"]
ORB_PBC_MARKET_FILTER_SYMBOLS = ["SPY", "QQQ"]

# Entry rules
ORB_PBC_OPENING_RANGE_MINUTES = 15
ORB_PBC_SIGNAL_WINDOW_START = "09:45"
ORB_PBC_SIGNAL_WINDOW_END = "11:15"
ORB_PBC_BREAKOUT_WINDOW_END = "11:00"
ORB_PBC_CHASE_GUARD_ATR = 2.5
ORB_PBC_PULLBACK_REF_ATR = 0.25
ORB_PBC_TRIGGER_OFFSET_DOLLARS = 0.01
ORB_PBC_TRIGGER_LIMIT_ATR = 0.05
ORB_PBC_VWAP_EXTENSION_MAX_ATR = 2.0
ORB_PBC_RVOL_BREAKOUT_MIN = 1.5
ORB_PBC_RVOL_TRIGGER_MIN = 1.3
ORB_PBC_SPREAD_PCT_MAX = 0.0005
ORB_PBC_MAX_ENTRIES_PER_SYMBOL_PER_DAY = 1
ORB_PBC_MAX_REARMS_PER_SYMBOL = 2
ORB_PBC_TRIGGER_EXPIRY_BARS = 4
ORB_PBC_MAX_RETRIES_PER_BREAKOUT = 1

# Market filters
ORB_PBC_STOCK_ATR_D_PCT_MIN = 0.015
ORB_PBC_STOCK_5M_ATR_PERCENTILE_MAX = 0.98
ORB_PBC_OR_WIDTH_MIN_ATR_D = 0.15
ORB_PBC_OR_WIDTH_MAX_ATR_D = 1.0
ORB_PBC_REGIME_SPY_ATR_PCT_PERCENTILE_MAX = 0.90
ORB_PBC_VWAP_CROSS_COUNT_MAX = 4
ORB_PBC_RVOL_LOOKBACK_DAYS = 20
ORB_PBC_ATR5M_LOOKBACK_DAYS = 20

# Exit rules
ORB_PBC_STOP_ATR_FLOOR = 0.6
ORB_PBC_STOP_ATR_NOISE = 0.05
ORB_PBC_MAX_STOP_DISTANCE_ATR = 1.5
ORB_PBC_SCALE_OUT_FRACTION = 0.5
ORB_PBC_SCALE_OUT_AT_R = 1.0
ORB_PBC_BREAKEVEN_AFTER_R = 1.0
ORB_PBC_BREAKEVEN_OFFSET_R = 0.1
ORB_PBC_CHANDELIER_MULTIPLE = 2.2
ORB_PBC_TIME_STOP_MINUTES = 30
ORB_PBC_TIME_STOP_MIN_R_TO_STAY = 0.5
ORB_PBC_EOD_FLATTEN_TIME = "15:50"

# Risk rules (integrates with, does not replace, risk/risk_gate.py)
ORB_PBC_EQUITY = 10000.0
ORB_PBC_RISK_PER_TRADE_PCT = 0.005
ORB_PBC_MAX_DAILY_LOSS_PCT = 0.01
ORB_PBC_MAX_TRADES_PER_DAY = 3
ORB_PBC_MAX_CONCURRENT_POSITIONS = 2
ORB_PBC_CORRELATED_PAIRS = [("NVDA", "AMD")]
ORB_PBC_CONSECUTIVE_FULL_STOP_LOSSES_LIMIT = 2
ORB_PBC_RISK_HALVING_AFTER_LOSING_DAYS = 4
ORB_PBC_RISK_HALVING_FACTOR = 0.5
ORB_PBC_MAX_NOTIONAL_EQUITY_MULTIPLE = 2.0
ORB_PBC_MAX_BUYING_POWER_UTILIZATION = 0.95

# Cost model
ORB_PBC_COMMISSION_PER_SHARE = 0.005
ORB_PBC_DEFAULT_SLIPPAGE_PER_SHARE = 0.01
ORB_PBC_TSLA_SLIPPAGE_PER_SHARE = 0.02
ORB_PBC_SLIPPAGE_STRESS_MULTIPLIER = 2.0

# Validation gates specific to ORB-PBC (layered on top of the generic
# validation/performance_gate.py backtest gate).
ORB_PBC_MIN_TRADES = 100
ORB_PBC_PF_MIN_AFTER_COSTS = 1.25
ORB_PBC_PF_MIN_BEFORE_COSTS = 1.35
ORB_PBC_AVG_R_MIN = 0.15
ORB_PBC_EXPECTANCY_MIN = 0.0
ORB_PBC_MAX_DRAWDOWN_PCT = 0.08
ORB_PBC_LONGEST_DRAWDOWN_MONTHS_MAX = 4
ORB_PBC_MAX_SYMBOL_PROFIT_SHARE = 0.40
ORB_PBC_BEST_SYMBOL_REMOVED_PF_MIN = 1.1
ORB_PBC_MONTHLY_PROFITABLE_PCT_MIN = 0.60
ORB_PBC_WF_EFFICIENCY_MIN = 0.5
ORB_PBC_WF_OOS_PROFITABLE_WINDOWS_MIN = 0.60
ORB_PBC_MC_P_DD_GT_10PCT_MAX = 0.10
ORB_PBC_MC_P_NEGATIVE_MAX = 0.20
ORB_PBC_SLIPPAGE_STRESS_PF_MIN = 1.0


# =========================
# OPTIONAL SYMBOL CONTROLS
# =========================
SYMBOL_BLACKLIST = set()
