import os

from dotenv import load_dotenv


load_dotenv()


# =========================
# TRADING MODE / GLOBAL GATES
# =========================
TRADING_MODE = os.getenv("TRADING_MODE", "PAPER_TRADING")
LIVE_ENABLED = os.getenv("LIVE_ENABLED", "false").lower() == "true"
GLOBAL_KILL_SWITCH = os.getenv("GLOBAL_KILL_SWITCH", "false").lower() == "true"
ALLOW_UNVALIDATED_STRATEGY = False


ETRADE_CONSUMER_KEY = os.getenv("ETRADE_CONSUMER_KEY")
ETRADE_CONSUMER_SECRET = os.getenv("ETRADE_CONSUMER_SECRET")
ETRADE_ENV = os.getenv("ETRADE_ENV", "sandbox")

# ALPACA MARKET DATA
ALPACA_API_KEY = os.getenv("ALPACA_API_KEY")
ALPACA_SECRET_KEY = os.getenv("ALPACA_SECRET_KEY")

ALPACA_BASE_URL = "https://paper-api.alpaca.markets"
ALPACA_DATA_URL = "https://data.alpaca.markets"
ALPACA_DATA_FEED = os.getenv("ALPACA_DATA_FEED", "iex")
# =========================
# ACCOUNT SETTINGS
# =========================
INITIAL_CAPITAL = 25000
PDT_MIN_EQUITY = 25000
MIN_EQUITY_BUFFER = 2000
DO_NOT_TRADE_BELOW_EQUITY = PDT_MIN_EQUITY + MIN_EQUITY_BUFFER


# =========================
# RISK SETTINGS
# =========================
MAX_POSITIONS = 2
MAX_CAPITAL_PER_TRADE = 0.10
MAX_PORTFOLIO_EXPOSURE = 0.40
MAX_DAILY_LOSS_PERCENT = 0.01
MAX_DAILY_LOSS_DOLLARS = 150
MAX_DRAWDOWN_PERCENT = 0.05
MAX_TRADES_PER_DAY = 5
LOSING_STREAK_COOLDOWN = 2
LOSING_STREAK_COOLDOWN_MINUTES = 120
MIN_TRADE_DOLLARS = 250
MAX_SECTOR_EXPOSURE = 0.25


# =========================
# MARKET SCANNER SETTINGS
# =========================
MIN_PRICE = 10.00
MAX_PRICE = 200.00
MIN_DAILY_VOLUME = 1000000
MIN_ABS_PERCENT_CHANGE = 0.10
MAX_SPREAD_PERCENT = 0.60
MIN_AVERAGE_VOLUME = 5000

MAX_SYMBOLS_TO_SCAN = 0
SNAPSHOT_POOL_SIZE = 120
MAX_DEEP_SCORE_CANDIDATES = 50
TOP_CANDIDATES_TO_TRADE = 20

INTRADAY_MINUTES_BACK = 180
MODEL_MINUTES_BACK = 180
BUY_START_TIME = "10:00"
BUY_END_TIME = "14:45"
FORCE_CLOSE_TIME = "15:55"


# =========================
# SNAPSHOT SCORING WEIGHTS
# =========================
WEIGHT_MOMENTUM = 0.6
WEIGHT_LIQUIDITY = 1.0
WEIGHT_SPREAD = 1.2

WEIGHT_SNAPSHOT_SCORE = 0.20
WEIGHT_INTRADAY_SCORE = 0.80


# =========================
# BUY / SELL THRESHOLDS
# =========================
BUY_SCORE_THRESHOLD = 7.0
RELAXED_BUY_SCORE_THRESHOLD = 5.5
RELAXED_BUY_AFTER_TIME = "13:30"
SELL_SCORE_THRESHOLD = -1.0
MIN_INTRADAY_SCORE = 1.5


# =========================
# PULLBACK STRATEGY FILTERS
# =========================
MIN_RETURN_3M = 0.0005
MIN_RETURN_5M = -0.0025
MIN_RETURN_15M = -0.015
MIN_RELATIVE_VOLUME = 0.80
MAX_RELATIVE_VOLUME = 2.10
REQUIRE_ABOVE_VWAP = True
MIN_BREAKOUT_POSITION = 0.15
MAX_BREAKOUT_POSITION = 0.38

MIN_DISTANCE_TO_MA50 = -0.03
MAX_DISTANCE_TO_MA50 = 0.06
MAX_BAR_RANGE_PERCENT = 0.035
MIN_EMA_RATIO = 0.9985


# =========================
# POSITION MANAGEMENT
# =========================
STOP_LOSS_PERCENT = 0.006
PROFIT_TARGET_PERCENT = 0.008

MIN_HOLD_MINUTES = 8
MAX_HOLD_MINUTES = 120
MAX_HOLD_DAYS = 3

MIN_SCORE_DROP_TO_SELL = 6.0
PROFIT_PROTECTION_SCORE_DROP = 4.5
PROFIT_PROTECTION_TRIGGER = 0.006
WEAKNESS_EXIT_HOLD_MINUTES = 12

REPLACEMENT_SCORE_BUFFER = 2.0
COOLDOWN_MINUTES = 90
MAX_BUYS_PER_SYMBOL_PER_DAY = 1


# =========================
# BACKTEST SETTINGS
# =========================
BACKTEST_SLIPPAGE_PERCENT = 0.0005
BACKTEST_COMMISSION_PER_SHARE = 0.0


# =========================
# VALIDATION GATES
# =========================
MIN_PAPER_TRADES_BEFORE_LIVE = 100
MIN_PROFIT_FACTOR_BEFORE_LIVE = 1.25
MIN_EXPECTANCY_BEFORE_LIVE = 0.0
MAX_VALIDATED_DRAWDOWN = 0.08


# =========================
# ACTIVE STRATEGY
# =========================
ACTIVE_STRATEGY = os.getenv("ACTIVE_STRATEGY", "momentum_scan_v1")
SCAN_MODE = os.getenv("SCAN_MODE", "market")
TRADE_SYMBOLS = []
MARKET_REGIME_SYMBOL = "QQQ"
USE_DAILY_REGIME = False
DAILY_REGIME_LAG_DAYS = 1

# Swing (daily trend) settings
SWING_ENTRY_START = "09:35"
SWING_ENTRY_END = "10:15"
SWING_STOP_LOSS_PERCENT = 0.08
SWING_PROFIT_TARGET_PERCENT = 0.50
SWING_MAX_HOLD_MINUTES = 60 * 24 * 30


# =========================
# MOMENTUM BREAKOUT STRATEGY
# =========================
STRATEGY_NAME = "momentum_breakout_v1"
RISK_REWARD_MINIMUM = 2.0
RSI_MIN = 50.0
RSI_MAX = 70.0
MOMENTUM_RVOL_MIN = 1.0
BREAKOUT_LOOKBACK = 20
REQUIRE_BREAKOUT = True
ATR_PERIOD = 14
ATR_STOP_MULTIPLE = 1.2
ATR_EXTREME_PERCENT = 0.025
TRAILING_STOP_R_MULTIPLE = 1.0


# =========================
# OPTIONAL SYMBOL CONTROLS
# =========================
SYMBOL_BLACKLIST = set()
